version: "2.4"
services:
  # rabbit_mq container uses the default rabbitmq image
  # exposes the ports
  # uses the specified volume
  rabbit_mq:

    # we use management image to get the
    # plugin for web dashboard
    image: rabbitmq:3.8-rc-management
    container_name: rabbit_mq
    ports:
        - '5672:5672'
        - '15672:15672'
    volumes:
      - rabbit_mqdata:/usr/share/rabbitmq/data
  # items_service:
  #   build: ./source/services/items
  #   networks:
  #     - my-network
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./db:/app/db
  orders_service:
    build: ./source/services/orders
    # networks:
    #   - my-network
    ports:
      - "5000:5000"
    depends_on:
        - rabbit_mq
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
    # volumes:
    #   - ./producer:/usr/src/app/producer
  sc_service:
    build: ./source/services/shopping_carts
    # networks:
    #   - my-network
    ports:
      - "6000:6000"
    volumes:
      - ./db:/app/db
    depends_on:
        - rabbit_mq
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
  # users_service:
  #   build: ./source/services/users
  #   networks:
  #     - my-network
  #   ports:
  #     - "7000:7000"
  #   volumes:
  #     - ./db:/app/db
networks:
  my-network:
    driver: bridge
volumes:
  rabbit_mqdata:
    driver: local